### ISSUE TITLE
Too many Requests

### ISSUE THREAD

**Issue by tushmesh** [DataThirstLtd/databricks.vsts.tools#27]
I am getting the below error very frequently.

2020-08-07T10:19:35.2242195Z ##[error]The remote server returned an error: (429) Too Many Requests.

system.debug also not gives much information. 
If I re-run the deployment again ( may be couple times) it succeeds.

What could be the reason?

![image](https://user-images.githubusercontent.com/39365355/89648642-29454900-d8dd-11ea-8be5-def5c91c0212.png)

**Comment by simondmorias** [comment]
That's a response from Databricks I'm afraid. It should happen when you overload the api. But there is no way this task is doing that, and I have seen this error before, usually it passes by itself.

**Comment by poornimaputtaswamy** [comment]
The Task created is triggering too many api calls, causing throttling in databricks webapp. Databricks WebApp limits 30 calls/sec, and the task is hitting the limit causing 429 throttling issue.

As this task is owned this git , we expect little help in modifying the task to either make less api calls or introduce a delay in api calls to databricks.

**Comment by simondmorias** [comment]
Please feel free to submit a pull request to address this. But I assure you the problem is not in this code. If you review it you will see that each task creates very few calls. Maybe if you upload a very large file you can create a lot of requests, but even then I find it hard to believe it will go over 30 a second. 
I believe that databricks rate limit at a higher level or you have another process running as well.
