### ISSUE TITLE
Unable to deploy a notebook to Databricks

### ISSUE THREAD

**Issue by souvik-ausnet** [DataThirstLtd/databricks.vsts.tools#29]
I am using a self hosted agent (Ubuntu one) and am trying to deploy a python notebook to an azure databricks workspace. This is the first time I am using this extension. I am using the 'Deploy Notebooks' task in Azure devops.
While using the same, I am getting the below error.-
2020-08-18T07:47:03.0952573Z ##[error]The***current***operating***system***is***not***capable***of***running***this***task.***That***typically***means***the***task***was***written***for***Windows***only.***For***example,***written***for***Windows***Desktop***PowerShell.
Is it true that this extension will not work for Ubuntu??

**Comment by simondmorias** [comment]
The task unfortunately does not support PS Core, only because when I originally wrote this there were no PS Core VSTS modules available. I'm not certain they are available now - but I suspect they will be.

The underlying PowerShell module is 100% Core compatible - so you could use that in a meantime - that Azure DevOps Tasks are just a UI wrapper to it.  https://github.com/DataThirstLtd/azure.databricks.cicd.tools
